---
abstract: unknown
author:
  - 'Thomas Linden <tlinden@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Crypt-PWSafe3
no_index:
  directory:
    - t
    - inc
requires:
  Crypt::CBC: 2.3
  Crypt::ECB: 1.45
  Crypt::Random: 1.25
  Crypt::Twofish: 2.14
  Data::UUID: 1.217
  Digest::HMAC: 1
  Digest::SHA: 1
  Shell: 0.5
version: 1.05
